import type { TowerDef, EnemyDef } from '../types';
import { COLORS } from './GameConfig';

export const TOWER_DEFS: Record<string, TowerDef> = {
  archer: {
    kind: 'archer',
    name: 'Mochi Bunny Archer',
    description: 'Fast single-target. Hits flying.',
    sellRefundRatio: 0.6,
    tiers: [
      {
        damage: 12,
        range: 180,
        fireRate: 1.6,
        cost: 50,
        hitsFlying: true,
        projectile: 'arrow',
        projectileSpeed: 600,
        color: COLORS.peach,
      },
      {
        damage: 22,
        range: 210,
        fireRate: 2.0,
        cost: 75,
        hitsFlying: true,
        projectile: 'arrow',
        projectileSpeed: 700,
        color: COLORS.peach,
      },
      {
        damage: 42,
        range: 240,
        fireRate: 2.6,
        cost: 110,
        hitsFlying: true,
        projectile: 'arrow',
        projectileSpeed: 800,
        color: COLORS.peach,
      },
    ],
  },
  mage: {
    kind: 'mage',
    name: 'Star Mage Kira',
    description: 'Splash magic damage. Hits flying.',
    sellRefundRatio: 0.6,
    tiers: [
      {
        damage: 18,
        range: 160,
        fireRate: 0.9,
        cost: 80,
        splashRadius: 50,
        hitsFlying: true,
        projectile: 'magicBolt',
        projectileSpeed: 500,
        color: COLORS.lavender,
      },
      {
        damage: 32,
        range: 180,
        fireRate: 1.1,
        cost: 110,
        splashRadius: 65,
        hitsFlying: true,
        projectile: 'magicBolt',
        projectileSpeed: 550,
        color: COLORS.lavender,
      },
      {
        damage: 58,
        range: 200,
        fireRate: 1.3,
        cost: 160,
        splashRadius: 80,
        hitsFlying: true,
        projectile: 'magicBolt',
        projectileSpeed: 600,
        color: COLORS.lavender,
      },
    ],
  },
  cannon: {
    kind: 'cannon',
    name: 'Acorn Bombardier Pebble',
    description: 'High splash damage. Ground only.',
    sellRefundRatio: 0.6,
    tiers: [
      {
        damage: 35,
        range: 150,
        fireRate: 0.55,
        cost: 100,
        splashRadius: 70,
        hitsFlying: false,
        projectile: 'cannonball',
        projectileSpeed: 380,
        color: COLORS.charcoal,
      },
      {
        damage: 60,
        range: 170,
        fireRate: 0.7,
        cost: 140,
        splashRadius: 85,
        hitsFlying: false,
        projectile: 'cannonball',
        projectileSpeed: 420,
        color: COLORS.charcoal,
      },
      {
        damage: 110,
        range: 200,
        fireRate: 0.85,
        cost: 200,
        splashRadius: 100,
        hitsFlying: false,
        projectile: 'cannonball',
        projectileSpeed: 460,
        color: COLORS.charcoal,
      },
    ],
  },
  frost: {
    kind: 'frost',
    name: 'Glacier Sprite',
    description: 'Slows enemies. Hits flying.',
    sellRefundRatio: 0.6,
    tiers: [
      {
        damage: 6,
        range: 150,
        fireRate: 1.4,
        cost: 60,
        slowFactor: 0.6,
        slowDuration: 1500,
        hitsFlying: true,
        projectile: 'frostShard',
        projectileSpeed: 480,
        color: COLORS.sky,
      },
      {
        damage: 12,
        range: 170,
        fireRate: 1.6,
        cost: 90,
        slowFactor: 0.5,
        slowDuration: 1800,
        hitsFlying: true,
        projectile: 'frostShard',
        projectileSpeed: 520,
        color: COLORS.sky,
      },
      {
        damage: 22,
        range: 200,
        fireRate: 1.9,
        cost: 130,
        slowFactor: 0.35,
        slowDuration: 2200,
        hitsFlying: true,
        projectile: 'frostShard',
        projectileSpeed: 560,
        color: COLORS.sky,
      },
    ],
  },
};

export const ENEMY_DEFS: Record<string, EnemyDef> = {
  slime: {
    kind: 'slime',
    name: 'Shadow Slime',
    stats: {
      maxHp: 40,
      speed: 55,
      goldReward: 8,
      damageOnLeak: 1,
      isFlying: false,
      scale: 1.0,
      color: COLORS.shadowMid,
    },
  },
  wolf: {
    kind: 'wolf',
    name: 'Shadow Wolf',
    stats: {
      maxHp: 70,
      speed: 110,
      goldReward: 14,
      damageOnLeak: 1,
      isFlying: false,
      scale: 1.0,
      color: COLORS.shadowDark,
    },
  },
  bat: {
    kind: 'bat',
    name: 'Shadow Bat',
    stats: {
      maxHp: 55,
      speed: 90,
      goldReward: 12,
      damageOnLeak: 1,
      isFlying: true,
      scale: 0.9,
      color: COLORS.plum,
    },
  },
  bear: {
    kind: 'bear',
    name: 'Shadow Bear',
    stats: {
      maxHp: 280,
      speed: 45,
      goldReward: 35,
      damageOnLeak: 2,
      isFlying: false,
      scale: 1.3,
      color: COLORS.shadowDark,
    },
  },
  boss: {
    kind: 'boss',
    name: 'Shadow King',
    stats: {
      maxHp: 1500,
      speed: 40,
      goldReward: 200,
      damageOnLeak: 5,
      isFlying: false,
      scale: 1.8,
      color: COLORS.plum,
    },
  },
};

export const GAME_BALANCE = {
  speedMultipliers: [1, 2, 3] as const,
  betweenWaveDelay: 5000,
  meteorDamage: 200,
  meteorRadius: 120,
  meteorCooldown: 30000,
  healAmount: 5,
  healCooldown: 60000,
  starThresholds: { full: 1.0, two: 0.6, one: 0.0 }, // ratio of remaining lives
};
